### PR TITLE
feat: add freeze judge & count <= 0 judge

### PR DESCRIPTION
**Pull request by Rabbitzzc**
Hei👏!
If an array USES 'object.freeze ()', the console will report an error, so add a condition.

image

### CODE REVIEW

**Comment by mreinstein** [comment]
Thanks for the PR! Two thoughts:
* curious about the cost of calling `isFrozen` every time we remove an item from an array; I'd hate to reduce performance by doing this run time check. I would think people that are drawn to this module are concerned about speed and memory performance, and wouldn't be passing frozen arrays anyway
* It might actually be better to just let the error propogate, rather than silently ignoring the failure.

Regardless, the `removeCount <= 0` check you added is valuable either way.

**Comment by Rabbitzzc** [comment]
> Thanks for the PR! Two thoughts:
> 
> * curious about the cost of calling `isFrozen` every time we remove an item from an array; I'd hate to reduce performance by doing this run time check. I would think people that are drawn to this module are concerned about speed and memory performance, and wouldn't be passing frozen arrays anyway
> * It might actually be better to just let the error propogate, rather than silently ignoring the failure.
> 
> Regardless, the `removeCount <= 0` check you added is valuable either way.

Thank you for your thoughts! You gave me some good ideas.👏

**Comment by mreinstein** [comment]
@Rabbitzzc  can you send another PR that just has the `removeCount <= 0` addition? I'll merge that immediately.

**Comment by mreinstein** [comment]
also. Please add a unit test for this new case :)

**Comment by Rabbitzzc** [comment]
> @Rabbitzzc can you send another PR that just has the `removeCount <= 0` addition? I'll merge that immediately.

Yes. I'm trying. At the same time, I'd like to discuss a problem with you.
```js
const removeItems = require('remove-array-items')
const arr = [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
removeItems(arr, -1, 4)  // arr = [5,,6,7,8]
```
but：
```
const arr = [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
arr.splice(-1,4) // arr = [1,2,3,4,5,6,7,8]
```
so, I have 2 ideas:
- judge
```js
if (startIdx >= length || removeCount <= 0 || startIdx < 0) {return}
```
- or 
```js
    let len = arr.length
    if (start + len <= 0) {
        start = 0
    } else if (start < 0) {
        start = start + len
    }

    let length = len - count
    if (start + count >= len) {
        arr.length = start
    } else {
        for (let i = start; i < length; ++i) {
            arr[i] = arr[i + count]
        }
        arr.length = length
    }
```

**Comment by Rabbitzzc** [comment]
> > @Rabbitzzc can you send another PR that just has the `removeCount <= 0` addition? I'll merge that immediately.
> 
> Yes. I'm trying. At the same time, I'd like to discuss a problem with you.
> 
> ```js
> const removeItems = require('remove-array-items')
> const arr = [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
> removeItems(arr, -1, 4)  // arr = [5,,6,7,8]
> ```
> 
> but：
> 
> ```
> const arr = [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
> arr.splice(-1,4) // arr = [1,2,3,4,5,6,7,8]
> ```
> 
> so, I have 2 ideas:
> 
> * judge
> 
> ```js
> if (startIdx >= length || removeCount <= 0 || startIdx < 0) {return}
> ```
> 
> * or
> 
> ```js
>     if (start + len <= 0) {
>         start = 0
>     } else if (start < 0) {
>         start = start + len
>     }
> 
>     let length = len - count
>     if (start + count >= len) {
>         arr.length = start
>     } else {
>         for (let i = start; i < length; ++i) {
>             arr[i] = arr[i + count]
>         }
>         arr.length = length
>     }
> ```

These problems may be encountered.😂

**Comment by mreinstein** [comment]
the function is designed with the expectation that both `start index` and `remove count` are `>= 0` it's safe to just check both of these conditions and bail out.

**Comment by Rabbitzzc** [comment]
> the function is designed with the expectation that both `start index` and `remove count` are `>= 0` it's safe to just check both of these conditions and bail out.

Thank you. I see you. the another pr https://github.com/mreinstein/remove-array-items/pull/10

**Comment by mreinstein** [comment]
closed in favor of #10

**Pull request closed without merging**
